# Development Dockerfile
FROM node:22

WORKDIR /app

# Copy package manager files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Expose the port for the development server
EXPOSE 8080

# Start the development server
CMD ["npm", "run", "dev", "--host", "0.0.0.0", "--port", "8080"]
