name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write   # necessario per push e release
  # Aggiunto il permesso per i deployment
  pages: write      # necessario per il deployment su Pages
  id-token: write   # necessario per verificare l'origine del deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # serve per lavorare con i tag

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Clean dist before pages build
        run: rm -rf dist
        working-directory: frontend

      - name: Build project (GitHub Pages)
        run: npm run build:ghpages
        working-directory: frontend

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  
